server:
  port: 8888
spring:
  application:
    name: gmall-gateway
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
#          filters:
#            - Auth
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: search-route  # 搜索服务路由
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: item-route
          uri: lb://item-service
          predicates:
            - Path=/api/item/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
gmall:
  jwt:
    pubKeyPath: D:\\ideaworkspace\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
